#Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 偉恩與咖啡
subtitle: 哲學、TRPG、雜談
description: 哲學普及與 TRPG 推廣。加上關於生活與社會的一些雜談。
keywords: 哲學, philosophy, TRPG
author: 洪偉 Wei Hung
language: zh-TW
timezone: Asia/Taipei

github_username: wayne930242
twitter_username: wayne930242
facebook_username: wayne930242

# archive page title
archive:
  title: 封存

# Build settings
anchorjs: false

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wayneh.tw
# cdn-url: "https://wayneh.tw/img/"
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

header-img: default.jpeg
email: wayne930242@gmail.com

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: true
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date

# Category & Tag
default_category: 其他
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

# Markdown-it config

markdown:
  render:
    html: true
    xhtmlOut: true
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ¶

theme: diaspora

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:wayne930242/wayne930242.github.io.git
  branch: master
  message: blog update

# Themes
google_analytics: 'UA-61272067-1'
ga_domain: wayneh.tw
disqus_username: waynehtw
favicon: https://wayneh.tw/favicon.png
mp3:
    - https://wayneh.tw/mp3/Touching_Moment.mp3
    - https://wayneh.tw/mp3/Dinner_for_Two.mp3
featured-tags: true
featured-condition-size: 1
rss: atom.xml
cover: https://wayneh.tw/img/default.jpg
post-default-img: "https://wayneh.tw/img/default.jpg"
post-default-img-mobile: "https://wayneh.tw/img/default.jpg"
menu:
 About: https://about.me/wayne930242
 哲學: https://wayneh.tw/categories/philosophy/
 TRPG: https://wayneh.tw/categories/TRPG/

# Disqus
disqus:
  enable: true
  disqus_shortname: waynetwhexo
  count: true

# Sidebar settings
sidebar: true
sidebar-about-description: "台大哲學博士生、哲學普及工作者， TRPG 玩家與專欄作家。"
sidebar-avatar: /avatar.jpg

# Qiniu imageView2 API
# clip-content: "?imageView2/1/w/1400/h/400/interlace/1/q/90"
# clip-avatar: "?imageView2/2/w/300/h/300/interlace/1/q/90"
# clip-post: "?" # you can custom post width and height
# clip-home-post-bg: "?imageView2/1/w/800/h/300/interlace/1/q/70"

math:
  engine: 'katex' # or 'mathjax' 
  mathjax:
    src: custom_mathjax_source
    config:
      # MathJax config
  katex:
    css: custom_css_source
    js: custom_js_source # not used
    config:
      # KaTeX config

pandoc:
  mathEngine: katex
